package com.codekul.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.codekul.database.domain.Car;
import com.codekul.database.domain.MyUser;

import com.codekul.database.dao.CarDao;
import com.codekul.database.dao.MyUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carDaoConfig;
    private final DaoConfig myUserDaoConfig;

    private final CarDao carDao;
    private final MyUserDao myUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carDaoConfig = daoConfigMap.get(CarDao.class).clone();
        carDaoConfig.initIdentityScope(type);

        myUserDaoConfig = daoConfigMap.get(MyUserDao.class).clone();
        myUserDaoConfig.initIdentityScope(type);

        carDao = new CarDao(carDaoConfig, this);
        myUserDao = new MyUserDao(myUserDaoConfig, this);

        registerDao(Car.class, carDao);
        registerDao(MyUser.class, myUserDao);
    }
    
    public void clear() {
        carDaoConfig.clearIdentityScope();
        myUserDaoConfig.clearIdentityScope();
    }

    public CarDao getCarDao() {
        return carDao;
    }

    public MyUserDao getMyUserDao() {
        return myUserDao;
    }

}
